---
title: "A Lifecycle Model for Chinese Urban Households"
author: "Zijian Wang"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    number_sections: yes
bibliography: RefLife.bib
---

```{=html}
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX:{
      equationNumbers:{ 
          autoNumber: "all"
          } 
      }
});
</script>
```
# Model Framework

## Objective Function

We assume time is discrete and the agent's preference is time-separable. The agent's instantaneous utility at age $t$, denoted by $u_t$, is a weighted sum of three separate terms: the utility from the agent's own health and consumption $u^1_t$, the utility from spending on her children $u^2_t$, and the utility from bequest $u^3_t$. Let $\kappa_1$ and $\kappa_2$ be the relative importance of spending on her children and leaving a bequest, we have:

$$ \label{eq:utility}
u_t = u^1_t + \kappa_1\cdot u^2_t + \kappa_3\cdot u^3_t 
$$

In each term, we use a CRRA-style utility function. For the first term, let $e_t$ be the agent's health status at age $t$ (greater $e_t$ for better health status), $C_t$ be her own consumption. Following @palumbo_uncertain_1999 and @de_nardi_why_2010, we define $u^1_t$ as a product of the agent's consumption utility and a multiplier $E(e_t)$:

$$
u^1_t = E(e_t)\cdot\frac{C_t^{1-\gamma}}{1-\gamma}
$$

where $\gamma$ is the coefficient of relative risk aversion. $E(e_t)$ is an monotonically increasing function of $e_t$, implying that health and consumption are complements to each other. We then construct $C_t$ by the Cobb-Douglas product of the quantity of non-housing consumption $c_t$ and of housing consumption $h_t$:

$$\label{eq:consumption}
C_t = c_t^\rho h_t^{1-\rho}
$$

As is pointed out in @cocco_portfolio_2005 and @yao_optimal_2005, the parameter $\rho$ in equation \eqref{eq:consumption} can be interpreted as the optimal proportion of non-housing consumption when the agent makes single-period consumption decisions. Hereafter, we assume the price per unit non-housing consumption and per unit housing consumption is 1 and $v_t$, and let $h_t$ also represent the size of house where the agent lives.

For the second term in equation \eqref{eq:utility}, we assume the agent's $u^2_t$ is decided by her children's consumption. If the agent has to supports more than one child at a time, we assume each child consumes equally. Let $n_t$ be the number of children she has to support at age $t$, $F_t$ be the consumption of each child, we have:

$$
u^2_t = n_t^\alpha\frac{F_t^{1-\gamma}}{1-\gamma}
$$

where $\alpha$ determines the impact of the number of children to support on the overall utility. We keep our setting in line with @barro_fertility_1989.

For the third term in equation \eqref{eq:utility}, we refer to @hubbard_importance_1994 that assumes the agent's life span is risky. Let $W_t$ be her net wealth at the end of age $t$, $\psi_t$ be the her survival probability at that moment, we have:

$$
u^3_t = (1-\psi_t) \frac{ W_t^{1-\gamma}}{1-\gamma}
$$

We assume the longest time she can live is $T$. Thus, when $t=T$, she dies with probability 1, i.e. $\psi_T=0$.

Let $\beta$ be the discounting factor, $V_t$ be the optimal state-value function for the agent. We can construct the following Bellman equation:

$$
V_t(s) = \max_a \{u_t(a,s) + \beta E_t[V_{t+1}(s)]|\Theta\}
$$

where $a$ and $s$ denote the sets of action and state variables, $\Theta$ denotes the set of parameters in the model.

There are three types of financial assets: short-term bond, long-term bond, and equity. The agent can allocate assets across them via two investment accounts: (1) A liquid savings account. She can deposit or withdraw money to or from this account at any time. (2) A tax-deferred defined-contribution pension account (referred to as "private pension account" hereafter). She can invest in this account each year prior to retirement, and withdraws funds from it after retirement. Meanwhile, the agent can invest in housing. We assume she can and can only either rent or own one house at a time.

Throughout the working life, the agent experiences the following six steps each year: (i) earning labor income and asset returns; (ii) making mandatory contribution to social insurances and housing fund; (iii) making voluntary contribution to private pension; (iv) paying income tax; (v) making investment decisions, paying for her own and her children's consumption, paying medical expenditure; (vi) dying at the end of year with probability $1-\psi_t$ . After retirement, the agent's labor incomes are replaced by pension benefits. Besides, she no longer needs to implement step (ii)-(iv).

One puzzle about China that has received considerable attention is why its household savings rate rose rapidly from the 1980s to the 2010s and has remained consistently at a high level. This cannot be simply explained by weak social security system, precautionary saving motive, or the increased ratio of working population. [^1] Some influential explanations focus on inter-generational transfer. For example, Curtis, Lugauer, and Mark [-@curtis_demographic_2015; -@curtis_demographics_2017] propose that the one-child policy, starting from 1980 and ending in 2016, led to a decline in family size, thus the Chinese parents can spend less in their children's consumption and have more to save. To capture this insight, we introduce the spending on children to the agent's objective function.

[^1]: For an introduction to the Chinese saving puzzle, see @modigliani_chinese_2004 or @chamon_why_2010.

## Income Process

### Labor Income

Let $y_t$ denote the agent's (real) pre-tax labor income.[^2] Let random variables $z^u_t$, $z^p_t$, $z^q_t$ be the employment status, permanent income shock, and transitory income shock. The deterministic part of labor income is represented by function $f_y(t,X_t)$, where $X_t$ is the agent's demographic features (gender and education).[^3] Employment status $z^u_t$ can only be 0 (employed) or 1 (unemployed), and $P\{z^u_t=1\}$ denotes the probability of being unemployed. Transitory shock $z^q_t$ follows an i.i.d. normal distribution. We assume permanent shock $z^p_t$ follows a AR(1) process with innovations drawn from a mixture of two normal distributions - this allows the distribution of income shock to have a negative skewness and high kurtosis, as is shown in @guvenen_nature_2014 and @guvenen_what_2021. Therefore, the agent's labor income is determined by

[^2]: Given the agent's nonmial pre-tax income $\tilde{Y}_t$ and price level $P_t$, we can calculate $y_t$ by $y_t = \tilde{Y}_t/P_t$. In estimation, we set $P_t=1$ in the first year of the panel data, and in the subsequent years, $P_t$ grows at the observed inflation rate. In simulation, we replace the observed inflation rate by a fixed rate $i_c$.

[^3]: For how to estimation $f_y(t,X_t)$, see @campbell_investing_2001 and @cocco_consumption_2005.

```{=tex}
\begin{equation}
\begin{split}
& y_t = (1-z^u_t)\cdot e^{f_y(t,X_t) + z^p_t + z^q_t} \\
& z^q_t \sim N(0,\sigma_q^2) \\
& z^p_t = \delta^pz^p_{t-1} + \eta_t \\
& \eta_t \sim \left\{
\begin{split}
& N(\mu_{\eta_1},\sigma_{\eta_1}) \; \text{with prob.} \,p_\eta \\
& N(\mu_{\eta_2},\sigma_{\eta_2}) \; \text{with prob.} \,1-p_\eta\\
\end{split}
\right. \\
& P\{z^u_t=1\} = 1/(1+e^{-f_u(t,z^p_t)})
\end{split}
\end{equation}
```
We assume $\mu_{\eta_1}p_\eta + \mu_{\eta_2}(1-p_\eta)=0$, and $\mu_{\eta,1}<0$. For simplicity, we set

$$
f_u(t,z^p_t) = \delta^u_0+\delta^u_1\cdot t+\delta^u_2\cdot z^p_t+\delta^u_3\cdot t\cdot z^p_t
$$

which is a linear function of age and permanent income shock.

### Pension Benefit

China's social security system consists of five social insurances and a housing fund.[^4] Every month during the working life, the agent and her employer make a mandatory contribution to these social security schemes (as long as she is employed). This contribution is tax-deductible. Normally, the annual contribution made by the agent herself is a fixed rate $\xi_c$ multiplied by a fraction (or all) of her salary for the previous year - the former is termed as "employee contribution rate", the latter is termed as "social security contribution base". We represent the agent's nominal income by $\tilde{Y}_t$, and her contribution base by $Y^B_t$. If she is unemployed in the previous year, that is, she is a new employee to the current company, then $Y^B_t$ will refer to her salary for the current year.

[^4]: The five social insurances are basic pension, medical insurance, unemployment insurance, maternity insurance, work injury insurance. We mainly focus on basic pension and medical insurance, for the contribution rates for other insurances are trivial ($\leq$ 0.5%) compared to the two.

Legally, the contribution base cannot be less than 0.6 times the province-wide average wage, or more than 3 times the province-wide average wage. Let $Y^*_t$ be the province-wide average wage, we can calculate $Y^B_t$ via:

$$
Y^B_t=\max\{\min\{\xi_b[\tilde{Y}_{t-1}z^u_{t-1}+\tilde{Y}_t(1-z^u_{t-1})],3Y^*_t\},0.6Y^*_t\}\times z^u_t
$$

where $\xi_b$ is a parameter between 0 and 1. When the agent is unemployed at age $t$, we set $Y^B_t=0$. For simplicity, we assume $Y^*_t$ is a AR(1) process.

In China's social security schemes, the highest employee contribution rate is for basic pension. Normally, an employee contributes 8% of her contribution base to the basic pension every month. In addition, her employer needs to contribute an amount equal to 16% of her contribution base to the pension.[^5] After retirement, the agent receives pension benefit each year, which replaces her labor income. This benefit is constituted by two parts: the first part, which we term as $B^1_t$, comes from a scheme called "fundamental pension"; the second part, which we term $B^2_t$, comes from the agent's "individual account pension".[^6] The amount of fundamental pension benefit is dependent on the agent's previous contributions as well as the province-wide average wage, while individual account pension benefit is dependent on the balance of her basic pension account.

[^5]: Before 2019, the employer's contribution rate to basic pension is 20%.

[^6]: Although this part of pension is called "individual account", individuals do not have control over how the assets are allocated in this account. Readers interested in China's pension system can find some useful information in @fang_chinese_2020, but please note the rules made after 2019 are not included.

To calculate pension benefit, we suppose the agent starts working at age $t_0$, retires at $t_{ret}$. The employee contribution rate to basic pension is $\xi_m$ ($\xi_m<\xi_c$), the employer's match contribution rate is $\xi_n$, the annuity rate for basic pension fund is $i_b$, the life expectancy in China is $t_{exp}$, the balance of the agent's basic pension account is $A^B_t$, where $A^b_{t_0}=0$. According to the official calculation rules, we define $B^1_t$ and $B^2_t$ by

$$
\label{eq:pension1}
B^1_t = \frac{1}{2}\left[\sum_{\tau=t_0}^{t_{ret}-1}\left(\frac{Y^B_\tau}{Y^*_\tau}\right) + \sum_{\tau=t_0}^{t_{ret}-1}z^u_{\tau}\right]\times Y^*_t\times1\% 
$$

$$
A^B_{t_{ret}}=\sum_{\tau=t_0}^{t_{ret}-1}
\left( A^B_\tau\cdot (1+i_b)+Y^B_\tau \cdot (\xi_m+\xi_n)\right)
$$

$$
\label{eq:pension2}
B^2_t =A^B_{t_{ret}} / 
\left(\frac{1-(1+i_b)^{-(t_{exp}-t_{ret})}}{1-(1+i_b)^{-1}}\right)
$$

We explain equation \eqref{eq:pension1}-\eqref{eq:pension2} briefly. $B^1_t$ equals to the average of the agent's indexed average wage and the province-wide average wage, multiplied by the number of years where she makes a contribution, then by 1%. The agent's indexed average wage refers to the average ratio of her contribution base to the province-wide average wage across the whole working life. After simplification, we obtain equation \eqref{eq:pension1}. $A^B_{t_{ret}}$ is the balance of the agent's basic pension account at retirement. $B^2_t$ equals to the annual withdrawal amount from the account that can remain constant from the retirement age $t_{ret}$ until the expected lifespan $t_{exp}$ is reached.

## Financial Assets

### Asset Markets

We assume the short-term bond return rate equals to a fixed risk-free rate, $i_f$. For the other assets, we assume their return rates follow a log-normal distribution. Let $\tilde{R}_{j,t}$ be the return of asset type $j$, we set $r^j_t=ln(\tilde{R}_{j,t})$, where $j\in\{l,e,h,m\}$. $r^l_t$ denotes log long-term bond interest rate, $r^e_t$ denotes log equity return rate, $r^h_t$ denote log housing price growth rate, $r^m_t$ denote log commercial mortgage rate. We use a VAR(1) model to simulate the fluctuation of each $r^j_t$:

$$ \textbf{r}_t = \delta^r_0+\delta^r_1* \textbf{r}_{t-1}+\epsilon_t
$$

where $\textbf{r}_t =[r^l_t,r^e_t,r^h_t,r^m_t]'$ is a four-dimension vector, $\epsilon_t$ follows a normal distribution with a mean of 0.[^7]

[^7]: One way to construct Chinese housing price indices is to divide Chinese urban area to Tier-1, Tier-2, Tier-3 and Tier-4 cities, then constructing housing price index for each tier. See @fang_demystifying_2016 for details.

### Investment Decisions

The agent has two investment accounts: a liquid savings account, and a private pension account. We use $A^L_t$ and $A^P_t$ to represent the balance of each account at the end of age $t$, $S^L_{j,t}$ and $S^P_{j,t}$ to represent the net flow into asset type $j$ in each account.

The balance of liquid savings account is determined by

$$
A^L_{t+1} = \sum_{j\in J} (\tilde{R}_{j,t+1}A^L_{j,t}+S^L_{j,t+1}) 
$$

where $A^L_{t+1} \geq -\bar{A}$, $\bar{A}$ denotes the agent's maximum credit limit. We assume the agent can take out some overdrafts when using short-term funds, but cannot short on long-term bond and equity. Therefore, $A^L_{j,t}\geq0$ for any $j\in\{l,e\}$.

In 2022, the Chinese government started offering a tax-deferred DC pension to its citizens, which is called "private pension". The private pension differs from basic pension in three ways: First, basic pension is mandatory, while private pension is voluntary and adopts an opt-in system. Second, the basic pension account is managed by National Social Security Fund, whereas private pension account is managed by the agent herself -- she can decide how much to invest (under a certain limit) and how to allocate the funds in this account. Third, basic pension is tax-free, while any withdrawal from the private pension account is taxed at 3%, i.e. the lowest rate of individual income tax.

The balance of private pension account is determined by $$
A^P_{t+1} = \sum_{j\in J} (\tilde{R}_{j,t}A^P_{j,t}+S^P_{j,t+1}) 
$$

Each year, net flow into the private pension account cannot exceed a certain limit. Hence, we set $S^P_{t+1}\equiv \sum_{j\in J} S^P_{j,t+1} \leq S_{\mathop{\max}}$, where $S_{\mathop{\max}}$ is the private pension saving limit. For all $j \in J$, $A^P_{j,t} \geq 0$. The domain for $S^P_t$ is $[0,\infty)$ when $t<t_{ret}$ and is $(-\infty,0]$ when $t\geq t_{ret}$. A negative $S^P_t$ implies the agent withdraws money from the account at age $t$.

## Housing

### Homeownership

Our settings about housing are similar to @cocco_portfolio_2005 and @yao_optimal_2005. The main difference is that when the agent borrows mortgage, in our model, she can either borrow commercial loan from a bank, or borrow a certain amount of housing fund loan from a government-run institute. This setting is based on China's housing provident fund system, a social security scheme that began to be implemented in 1999. The Chinese government referred to Singapore's Central Provident Fund scheme when designing the system. According to this system, an employee is required to contribute a certain portion of her pre-tax salary to a housing fund account every month. This contribution is normally 5%-12% of her social security contribution base. Her employer is also required to contribute an equal amount. These funds are managed by Housing Provident Fund Management Center run by each local authority, and can only be used for purchasing, decorating, repairing or renting houses. Individuals who have contributed to the housing fund can apply for a subsidized loan (under a certain limit) from the management center on their first and second home purchase. When an employee retires and has already repaid the loan, she can redeem the remaining funds in her housing fund account.

Let $\phi_{rp}$ be the rent-to-price ratio, $v_t$ be housing price, $o_t$ be the agent's homeonwership choice, $K_t$ be her housing expenditure (including renting and buying). We set $v_{t+1}=(1+r^h_t)v_t$. If the agent is a homeowner at age $t$, then $o_t = 1$; otherwise, $o_t = 0$. Negative $K_t$ implies a selling of home. If the agent borrows a mortgage, the loan-to-value ratio she faces is $\phi_{lv}$ and the mortgage term is $m$. The transaction cost for home buying is $\phi_{buy}$ of the house value. As we mentioned, $h_t$ denotes the quantity of housing service she consumes at age $t$. We assume the agent either rents or owns only one home at a time.[^8]

[^8]: This setting is plausible because of the strict home purchase restrictions in many Chinese cities. Normally, individuals face higher downpayments and higher mortgage rates for the purchase of their second or third home, and they cannot apply for housing fund loans on their third home purchase. In Tier-1 and Tier-2 cities, the eligibility to purchase newly-built housing is usually determined by a lottery system. People not owning a house have a higher chance of winning the lottery.

When the agent keeps to be a pure renter at $t+1$, we set$$
K_{t+1}\{o_t = 0,o_{t+1} = 0\} = 
\phi_{rp} v_{t+1}h_{t+1}
$$ When the agent buys a home at $t+1$, i.e. becoming a homeowner,

```{=tex}
\begin{equation}
\begin{split}
& K_{t+1}\{o_t = 0,o_{t+1} = 1\} \leq (1+\zeta_b)v_{t+1}h_{t+1}\\
& K_{t+1}\{o_t = 0,o_{t+1} = 1\} \geq (1-\phi_{lv}+\phi_{buy})v_{t+1}h_{t+1}
\end{split}
\end{equation}
```
We assume the agent keeps living in her own home until selling it. The agent's mortgage debt consists of both commercial loan and housing fund loan. Let $D_t$ be the agent's mortgage debt ($D_t\geq0$), $D^H_t$ denote the agent's outstanding housing fund loan ($0\leq D^H_t\leq D_t$) . The interest rate for housing fund loan is $i_d$ lower than the commercial mortgage rate $\tilde{R}_{m,t}$. If she borrows at $t+1$, she has to repay the debt in each subsequent period.

```{=tex}
\begin{equation}
D_{t+1} = \left\{
\begin{split}
& v_{t+1}h_{t+1}-K_{t+1} & \; \text{if} \; o_t = 0,o_{t+1} = 1 \\
& (\tilde{R}_{m,t}-i_d)D^H_t + \tilde{R}_{m,t}(D_t-D^H_t) - K_{t+1} & \; \text{if} \;o_t=1,o_{t+1}=1, D_t>0 \\
& 0 & \; \text{else}
\end{split}\right.
\end{equation}
```
Before paying off the mortgage, i.e. $D_t>0$, the agent is not allowed to change or sell the home, or borrow a new mortgage. Under this circumstance, the domain for $o_{t+1}$ is $\{1\}$ and the domain for $h_{t+1}$ is $\{h_t\}$ (otherwise they will be $\{0,1\}$ and $[0,\infty)$).

In each installment, the repayment she made should be no less than a minimum limit. Therefore,

```{=tex}
\begin{equation}
\begin{split}
& K_{t+1}\{o_t=1,o_{t+1}=1,D_t>0\} \geq \Phi^{HFL}_{t+1} D^H_t + \Phi^{CL}_{t+1}(D_t - D^H_t) \\
& K_{t+1}\{o_t=1,o_{t+1}=1,D_t>0\} \leq D_t \\
& K_{t+1}\{o_t=1,o_{t+1}=1,D_t=0\} = 0
\end{split}
\end{equation}
```
where $\Phi^k_t$ ($k\in\{CL,HFL\}$) denotes the ratio of minimum repayment to debt for each loan type ($CL$ denotes commercial loan, $HFL$ denotes housing fund loan). We set that if she pays the equal amount each year for the remaining mortgage term, then this amount is the minimum repayment. Therefore,

$$
\Phi^k_t = {i_{k,t}}^{-1}/\left(\frac{1-{i_{k,t}}^{-(m^k_t+1)}}{1-{i_{k,t}}^{-1}}\right)
$$

where $k\in\{CL,HFL\}$, $i_{CL,t} = \tilde{R}_{m,t}$, $i_{HFL,t} = \tilde{R}_{m,t} - i_b$. $m^k_t$ denotes the length of remaining mortgage term for loan type $k$, and

```{=tex}
\begin{equation}
m^{CL}_{t+1} = \left\{
\begin{split}
& m & \; \text{if} \; o_t = 0,o_{t+1} = 1 \\
& m^{CL}_t - 1 & \; \text{if} \;o_t=1, o_{t+1}=1, D_t-D^H_t>0 \\
& 0 & \; \text{else}
\end{split}\right.
\end{equation}
```
```{=tex}
\begin{equation}
m^{HFL}_{t+1} = \left\{
\begin{split}
& \min\{m,t_{ret}-t\}\; & \; \text{if} \; o_t = 0,o_{t+1} = 1 \\
& m^{HFL}_t - 1 & \; \text{if} \;o_t=1, o_{t+1}=1, D^H_t>0 \\
& 0 & \; \text{else}
\end{split}\right.
\end{equation}
```
where the maximum mortgage term is $\min\{m,t_{ret}-t\}$, implying that the housing fund loan should be paid off before retirement.

When the agent sells a house at $t+1$,

$$
K_{t+1}\{o_t=1,o_{t+1}=0\} = -v_{t+1}h_{t+1}
$$

### Housing Fund

During the working life, the agent's annual contribution to the housing fund account is $\xi_h$ ($\xi_h<\xi_c$) multiplied by her contribution base. Her employer's match contribution is at the same amount. The funds in housing fund account grow at the risk-free rate $i_f$. At retirement, the agent redeems all the funds from the account. Let $A^H_t$ denote the balance of housing fund account, $K^H_t$ denote the money withdrawn from the account, then

```{=tex}
\begin{equation}
A^H_{t+1}= \left\{
\begin{split}
& (1+i_f)A^H_t+2\xi_h Y^B_{t+1} - K^H_{t+1} \;& \text{if} \; t+1<t_{ret}\\
& 0 \;& \text{if} \; t+1 \geq t_{ret}\\
\end{split}
\right.
\end{equation}
```
where $0\leq K^H_{t+1}\leq K_{t+1}$, $A^H_{t+1}\geq 0$.

The agent's debt on housing fund loan is

$$
D^H_{t+1} = \left\{
\begin{split}
& \min\{\phi_h A^H_t,\bar{D}_{H},D_{t+1}\} \;& \text{if} \;o_t=0,o_{t+1}=1\\
& (\tilde{R}_{m,t}-i_d)D^H_t - K^H_{t+1} \;& \text{if} \;o_t=1,o_{t+1}=1,D^H_t>0\\
& 0 \;& \text{else}
\end{split}
\right.
$$ where $\phi_h$ denotes the ratio of housing fund loan limit to the agent's housing fund account balance in the previous year, $\bar{D}_{H}$ denotes the maximum limit of housing fund loan.When the agent is a pure renter,i.e. $o_t=0$, she can also use housing fund to pay her rent. In this case, $K^H_t \leq \phi_{rp} v_{t+1}h_{t+1}$.

## Supplementary Health Insurance

Like @duarte_simple_2021, we consider the agent's working life and retirement life separately. Throughout the working life, the agent keeps a good health status and does not need to concern about medical expenditure. After retirement, her health status shifts between several values randomly and she spends in medical care each year, according to her age, health status, and income.

Following @koijen_health_2016, we assume the agent's health status $e_t$ is one of $\{0,e,1\}$, where $e_t=0$ indicates death, $e_t=e$ indicates bad status, $e_t =1$ indicates good status ($0<e<1$), and $E(e_t)=(e_t)^\gamma$. Before retirement, we set $e_t=1$. After retirement, we denote the transition probability between the health status by $P\{e_{t+1}|e_t\}$ and set $e_t=0$ (death) is a absorbing status. Thus, $P\{0|0\}=1$; the agent's survival probability at the end of $t$, conditional on $e_t$, is:

$$
\psi_{t+1}|e_t = 1-P\{0|e_t\}
$$

Let $M_t$ denote the agent's out-of-pocket medical expenditure at age $t$. Before retirement and at the time of death, $M_t=0$. The deterministic part of log medical expenditure is given by $f_m(t,e_t,y_t)$. Following @french_distribution_2004 and @de_nardi_why_2010, we have:

```{=tex}
\begin{equation}
\begin{aligned}
& \ln(M_t)=f_m(t,e_t,y_t)+\zeta^p_t + \zeta^q_t \\
& \zeta^p_t = \delta^{\zeta}\zeta^p_{t-1}+\omega_t \\
& \omega_t \sim N(0,\sigma_{\omega})\\
& \zeta^q_t \sim N(0,\sigma_{\zeta})
\end{aligned}
\end{equation}
```
where $\zeta^p_t$ is the permanent shock on medical expenditure, $\zeta^q_t$ is the transitory shock on medical expenditure. $\zeta^p_t$ follows a AR(1) process with a normally-distributed innovation, $\zeta^q_t$ follows a normal distribution.

Our setting about supplementary health insurance is similar to @koijen_health_2016. The main difference is that @koijen_health_2016 assumes that people can buy multiple insurances with different maturities at each age, whereas for simplicity, we assume the agent buys an insurance that requires she to contribute a fixed amount of premium each year throughout the working life (from $t_0$ to $t_{ret}-1$), and this insurance is valid until her death. The supplementary health insurance can cover the difference in medical expenditure between good health status and bad health status. Suppose the fixed premium is $g$, asset in the insurance account grows at risk-free rate, and the insurer makes no profit from this insurance, then

$$
g=\frac{i_f}{(1+i_f)^{t_{ret}-t_0}-1}\sum_{t=t_{ret}}^T \frac{\psi^e_t\cdot \Delta M_t}{(1+i_f)^{t-t_{ret}+1}}
$$ where $\psi^e_t$ is the unconditional probability of $e_t=e$. Let $M_t\{e_t=1\}$ and $M_t\{e^t=e\}$ be the medical expenditure under good and health status with all the others equal at age $t$ ($t\geq t_{ret}$), then $\Delta M_t = M_t\{e_t=1\}-M_t\{e^t=e\}$. We allow the agent to buy only a fraction of the supplementary health insurance. Therefore, throughout the working life, she pays $\phi_e \cdot g$ ($0<\phi_e<1$) for the supplementary health annually, and after retirement, the insurer pays off $\phi_e$ of the agent's $\Delta M_t$ each year.

## Budget Constraints

The agent's income tax $f_t(Y^{tax}_t)$ is a function to of the taxable income $Y^{Tax}_t$. In China, taxable income is the agent's nominal income minus social security contribution and special additional deductions, then minus tax-exempt income threshold. As is mentioned above, the agent's social security contribution is $\xi_cY^B_t$. Four elements in our model are included in special additional deductions: private pension savings, spending on children, housing expenditure, medical expenditure. Private pension savings can be deducted before tax is calculated. The deduction for every child supported by the agent, housing rent and mortgage repayment each is a fixed amount $\Gamma_n$ per year. Medical expenses in excess of a fixed amount $\underline{\Gamma}$ (given that the agent's health status is bad) is also deductible, and the maximum deduction for medical expenses is $\Gamma_e$. Let $\underline{Y}$ denote the tax-exempt income threshold. Then we can calculate the agent's taxable income by

$$
Y^{Tax}_t = \max\{0,\tilde{Y_t} - \xi_cY^B_t - S^P_t - \Gamma_n(n_t+\textbf{1}\{o_t=0\}+\textbf{1}\{o_t=1,D_t>0\}) - (M_t\textbf{1}\{e_t=e\}-\underline{\Gamma},\Gamma_e)-\underline{Y}\}
$$

Therefore, the agent's post-tax income is

```{=tex}
\begin{equation}
Y_t = \left\{
\begin{split}
& \tilde{Y}_t - f_t(Y^{Tax}_t) \;& \text{if} & \;t< t_{ret}\\
& B^1_t +B^2_t \;& \text{if} &\;t\geq t_{ret}\\
\end{split}
\right.
\end{equation}
```
The agent's net wealth is the sum of her basic pension account balance, private pension account balance, liquid savings account balance, housing fund account balance, housing value minus mortgage debt (if she is a homeowner):

$$
W_t = A^B_t+A^P_t+A^L_t+A^H_t+o_tv_{t}h_t-D_t
$$

Before retirement:$$
c_t = \max\{Y_t - n_tF_t - (K_t - K^H_t) - \phi_e g - S^L_t,\underline{c}\}
$$

After retirement:

$$
c_t = \max\{Y_t + A^H_t \textbf{1}\{t=t_{ret}\} - n_tF_t - K_t - (1-\phi_e)M_t -(1-\xi_p)S^P_t - S^L_t,\underline{c}\}
$$ where $\xi_p$ is the tax rate for withdrawals from private pension account.

# Parametrization

table

| Parameter                   | Description                                                      |  Value  | Source                     |
|------------------|-------------------|:----------------:|------------------|
| Age                         |                                                                  |         |                            |
| $t_0$                       | age of start working                                             |   20    | Calibration                |
| $t_{ret}$                   | age of retirement                                                |   60    | Calibration                |
| $t_{exp}$                   | life expectancy                                                  |   75    | Calibration                |
| $T$                         | maximum lifespan                                                 |   99    | Calibration                |
| Preferences                 |                                                                  |         |                            |
| $\alpha$                    | concavity for the impact of the number of children on utility    |  0.76   | @curtis_demographic_2015   |
| $\beta$                     | discounting factor                                               |  0.99   | @calvet_cross-section_2021 |
| $\gamma$                    | relative risk aversion                                           |  5.24   | @calvet_cross-section_2021 |
| $e$                         | bad health status                                                |  0.74   | @koijen_health_2016        |
| $\kappa_1$                  | importance of spending on children                               |         |                            |
| $\kappa_2$                  | bequest motive                                                   |         |                            |
| Asset Markets               |                                                                  |         |                            |
| $i_b$                       | annuity rate                                                     |   4%    | Calibration                |
| $i_c$                       | inflation rate                                                   |   2%    | Calibration                |
| $i_d$                       | spread between commercial mortgage and housing fund loan         |   2%    | Calibration                |
| $i_f$                       | risk-free rate                                                   |   2%    | Calibration                |
| Social Security             |                                                                  |         |                            |
| $\xi_b$                     | ratio of contribution base to labor income                       |  100%   | Calibration                |
| $\xi_c$                     | employee contribution rate to all social security schemes        |   15%   | Chinese gov.               |
| $\xi_m$                     | employee contribution rate to basic pension                      |   8%    | Chinese gov.               |
| $\xi_h$                     | employee contribution rate to housing provident fund             |   5%    | Chinese gov.               |
| $\xi_n$                     | employer's match contribution rate to basic pension              |   16%   | Chinese gov.               |
| $\xi_p$                     | tax rate for withdrawals from private pension                    |   3%    | Chinese gov.               |
| Housing and Investment      |                                                                  |         |                            |
| $\bar{A}$                   | maximum credit limit                                             | 50,000  | calibration                |
| $\bar{D}_H$                 | maximum limit of housing fund loan                               | 600,000 | calibration                |
| $S_{max}$                   | private pension saving limit                                     | 12,000  | Chinese gov.               |
| $\phi_{rp}$                 | rent-to-price ratio                                              |  1/600  | calibration                |
| $\phi_{buy}$                | transaction-cost-to-home-value ratio in home buying              |   5%    | calibration                |
| $\phi_{lv}$                 | loan-to-value ratio                                              |   0.7   | calibration                |
| $\phi_{h}$                  | ratio of housing fund loan limit to housing fund account balance |   15    | calibration                |
| $m$                         | mortgage term                                                    |   20    | calibration                |
| Tax and Government Transfer |                                                                  |         |                            |
| $\Gamma_n$                  | pre-tax deduction for each child (and housing)                   | 12,000  | Chinese gov.               |
| $\Gamma_e$                  | maxmium pre-tax deduction for medical expenses                   | 80,000  | Chinese gov.               |
| $\underline{\Gamma}$        | pre-tax deduction threshold for medical expenses                 | 15,000  | Chinese gov.               |
| $\underline{Y}$             | tax-exempt income threshold                                      | 60,000  | Chinese gov.               |
| $\underline{c}$             | consumption floor                                                | 3,6000  | calibration                |

# Appendix: Special Additional Deductions
